services:
  mysql:
    image: mysql:8.4
    container_name: triagedesk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ticketdb
      MYSQL_USER: triage
      MYSQL_PASSWORD: triagepass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: