server.port=8081
spring.application.name=ticket-service

spring.datasource.url=jdbc:mysql://localhost:3307/ticketdb
spring.datasource.username=triage
spring.datasource.password=triagepass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration